subcomponents:
  nfs-server-provisioner:
    namespace: kube-system
    injectNamespace: true
    config:
      image:
        repository: quay.io/kubernetes_incubator/nfs-provisioner
        tag: v2.3.0
      persistence:
        enabled: true
        storageClass: "-"
        size: 200Gi
      storageClass:
        default: false
      nodeSelector:
        node-role.kubernetes.io/nfs: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
  consul:
    namespace: kube-system
    injectNamespace: true
    config:
      server:
        enabled: true
        storageClass: nfs
        storage: 10Gi
      tests:
        enabled: false

  vault:
    namespace: kube-system
    injectNamespace: true
    config:
      injector:
        enabled: false
      server:
        standalone:
          enabled: "false"
        ha:
          enabled: "true"
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "consul" {
              path = "vault"
              address = "HOST_IP:8500"
            }
  vault-secrets-operator:
    namespace: kube-system
    injectNamespace: true
    config:
      # image:
      #   repository: ricoberger/vault-secrets-operator
      #   tag: 1.2.3
      replicaCount: 1
      deploymentStrategy:
        type: Recreate
      vault:
        address: "http://vault:8200"
        authMethod: kubernetes
        kubernetesPath: auth/kubernetes
        kubernetesRole: vault-secrets-operator
        reconciliationTime: "300"
